version: '3.3'
services:

  api:
    build:
      context: ./
      dockerfile: ./build_new/api/Dockerfile
    command: 'uvicorn --fd 0 api.api:app --host="0.0.0.0"  --port=8090 --reload'
    restart: always
    env_file: .env

    volumes:
      - ./src/backend:/backend
      - ~/.ssh/id_rsa:/root/id_rsa.pem
      - ./build_new/api:/ssl
      - ./data:/data

    environment:
      - PYTHONPATH=/backend/code
      - SET_CORS=no
      - PYTHONUNBUFFERED=1
      - OMP_THREAD_LIMIT=1
    
    depends_on: 
      - mongodb

    ports:
      - "${API_PORT:-8090}:8090"


  jupyter:
    build:
      context: ./
      dockerfile: ./build_new/api/Dockerfile
    command: 'jupyter lab --allow-root --no-browser --port 8888 --ip=0.0.0.0 --ServerApp.password="$TK_JUPYTER_PASSWD_HASH"'
    restart: on-failure
    env_file: .env

    volumes:
      - ./src/backend:/backend
      - ~/.ssh/id_rsa:/root/id_rsa.pem
      - ./build/api/files:/ssl
      - ./data:/data

    environment:
      - PYTHONPATH=/backend/code
      - SET_CORS=no
      - PYTHONUNBUFFERED=1

    ports:
      - "${JUPYTER_PORT:-8888}:8888"

  mongodb:
    image: mongo:latest
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=needstrongpassword
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - ${MONGO_PORT:-27017}:27017
    privileged: true
  