name: Deploy to Hetzner
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 --decode > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/deploy_key
          echo -e "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile /dev/null\n" > ~/.ssh/config

      - name: Deploy to Server
        env:
          VCS_TOKEN: ${{ secrets.VCS_TOKEN }}
        run: |
          ssh -i ~/.ssh/deploy_key ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "bash -s" << EOF
            cd ${{ secrets.APP_LOCATION }}
            
            # Configure git to use HTTPS instead of SSH
            git config --global url."https://github.com/".insteadOf git@github.com:
            git config --global credential.helper 'store --file=/tmp/git-credentials'
            echo "https://${VCS_TOKEN}@github.com" > /tmp/git-credentials
            
            # Ensure we're using HTTPS URL
            git remote set-url origin https://github.com/rajathy2020/sahayak.git
            
            git stash -u
            git stash -k
            git stash
            git pull origin main
            docker compose restart api
            docker compose up -d --build --force-recreate --no-deps web

            
            