name: Deploy Deeksha VM
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install SSH Key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 --decode > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/deploy_key
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Restart API and Nginx
        run: |
          ssh -i ~/.ssh/deploy_key ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'ENDSSH'
            cd ${{ secrets.APP_LOCATION }}
            git config --global credential.helper 'store --file=/tmp/git-credentials'
            echo "${{ secrets.VCS_TOKEN }}" > /tmp/git-credentials
            git stash -u
            git stash -k
            git stash
            git pull origin main
            docker compose restart api
            docker compose up -d --build --force-recreate --no-deps web
          ENDSSH
