name: Deploy to Hetzner
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 --decode > ssh_key
          chmod 600 ssh_key
          eval "$(ssh-agent -s)"
          ssh-add ssh_key

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no -i ssh_key ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "sudo bash -s" << 'ENDSSH'
            cd ${{ secrets.APP_LOCATION }}
            git config --global credential.helper 'store --file=/tmp/git-credentials'
            echo "${{ secrets.VCS_TOKEN }}" > /tmp/git-credentials
            git stash -u
            git stash -k
            git stash
            git pull origin main
            docker compose down
            docker compose up -d --build
ENDSSH 