name: Deploy Deeksha VM
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 --decode > ssh_key
          echo "Base64 key starts with: $(echo ${{ secrets.SSH_PRIVATE_KEY }} | cut -c1-10)..."
          echo "Base64 key ends with: ...$(echo ${{ secrets.SSH_PRIVATE_KEY }} | rev | cut -c1-10 | rev)"
          chmod 600 ssh_key
          eval "$(ssh-agent -s)"
          ssh-add ssh_key

      - name: Restart API and Nginx
        run: |
          ssh -o StrictHostKeyChecking=no -i ssh_key ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "sudo bash -s" << 'ENDSSH'
            cd ${{ secrets.APP_LOCATION }}
            git config --global credential.helper 'store --file=/tmp/git-credentials'
            echo "${{ secrets.VCS_TOKEN }}" > /tmp/git-credentials
            git stash -u
            git stash -k
            git stash
            git pull origin main
            docker compose restart api
            docker compose up -d --build --force-recreate --no-deps web
